### ISSUE TITLE
Yesod and Websockets

### ISSUE THREAD

**Issue by JorisM** [alephcloud/wai-cors#12]
I'm using yesod and wai-cors. Everything works great, except for when I send a websocket request with wai-cors middleware enabled, I get a 500 internal server error. When I take out the wai-cors middleware, everything works as expected. Is there any way you could exclude ws requests to go through wai-cors?

PS: Thanks for the library, helped me a bunch so far.

**Comment by JorisM** [comment]
The gzip middleware had a similar problem: 
https://github.com/yesodweb/wai/issues/265

fix could be along the lines of: 
https://github.com/yesodweb/wai/commit/5b1a7e384fc49bc9b17e9d517fd99423e8ebf74e

**Comment by JorisM** [comment]
in the meantime I have this workaround to add the auth header, but ignore cors when a sockets request comes in:

``` haskell
addAuthHeader :: CorsResourcePolicy -> CorsResourcePolicy
addAuthHeader r =
    r { corsRequestHeaders = "Authorization" : simpleHeaders }

isSocketRequest :: Request -> Maybe CorsResourcePolicy
isSocketRequest req =
    case WaiWS.isWebSocketsReq req of
        True -> Nothing
        False -> (Just $ addAuthHeader simpleCorsResourcePolicy)

simpleCorsWithAuth :: Wai.Middleware
simpleCorsWithAuth = cors isSocketRequest
```

**Comment by larskuhtz** [comment]
The fix at yesodweb/wai@5b1a7e3 looks pretty simple. Do you know if for CORS it is the correct behavior to just do nothing for web socket requests? I haven't used CORS for some time, so I don't remember. If doing nothing is actually the right thing to do, a fix would be easy.

Thanks a lot for investigating this!

**Comment by JorisM** [comment]
I googled for a while, but I can't find any specs for cors with websockets. I will look into it some more and report back.

**Comment by larskuhtz** [comment]
It seems that websocket support the `Origin` header in the requests but don't support any further elements of CORS. This would mean that any origin policy would have to be enforced by the server, which is (currently) outside of the scope of this package. (CORS policy is in first place enforced by the client, the server only provides the client with the needed information.)

Therefor I decided to solve this issue by just ignoring websocket requests completely in the cors middleware. I added a note to the documentation that reminds application authors to check if the `Origin` header is present and possibly  take the needed actions.

Do you think that this is an acceptable solution for this issue? And if so, could you please test your code with the latest version of wai-cors from https://github.com/alephcloud/wai-cors (note that this is a different repository) and let me know if everything works?

**Comment by larskuhtz** [comment]
Development of this package moved to https://github.com/alephcloud/wai-cors.

**Comment by jonsterling** [comment]
@larskuhtz I'm a little confused; this is alephcloud/wai-cors here... Did you mean to link to https://github.com/larskuhtz/wai-cors?

**Comment by larskuhtz** [comment]
@jonsterling, yes, the new location is https://github.com/larskuhtz/wai-cors. Thanks for spotting this.

However I just regained access to this repository. So development may switch back to this repository before the next hackage release.

**Comment by JorisM** [comment]
Yes, this works for me. I will test asap.

**Comment by larskuhtz** [comment]
I release a [new version (0.2.3) on hackage](http://hackage.haskell.org/package/wai-cors-0.2.3). Let me know if this doesn't work for you.

I am going to close this issue. I moved development to https://github.com/larskuhtz/wai-cors. Feel free to open a new issue there if you encounter any problems.

**Comment by JorisM** [comment]
tested 0.2.3 and works like a charm! thanks :smile:
