### ISSUE TITLE
wai-cors fails when an empty Access-Control-Request-Headers is sent

### ISSUE THREAD

**Issue by exFalso** [alephcloud/wai-cors#8]
This is due to the use of sepBy1 at https://github.com/alephcloud/wai-cors/blob/3b86a65f968778b9/src/Network/Wai/Middleware/Cors.hs#L467

Access-Control-Request-Headers is a "#" list of field-names as per the W3C recommendation http://www.w3.org/TR/cors/#access-control-request-headers-request-header
A hash list in turn is a comma separated list of **zero** or more elements as per http://tools.ietf.org/html/rfc2616#section-2.1 or for an updated RFC see https://tools.ietf.org/html/rfc7230#section-7.
It only means "one or more" if it is written as 1#field-name

**Comment by larskuhtz** [comment]
Fixed in 60720c283fabced40e7882beeff025bc6f6507e9. Thanks for the detailed report!
